#!/bin/bash
set -e
go build shenzhen-go/...
go test shenzhen-go/client/view \
  shenzhen-go/examples \
  shenzhen-go/model \
  shenzhen-go/server \
  shenzhen-go/server/view \
  shenzhen-go/source 
exit 0
